# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:48
from __future__ import unicode_literals

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20161218_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4(), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4(), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4(), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='hub.Container'),
        ),
    ]
